//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.06 at 10:07:24 AM ICT 
//


package com.xmlwriter.example.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataRekeningType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataRekeningType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="infoRekening" type="{}infoRekeningType" minOccurs="0"/>
 *         &lt;element name="mutasiRekening" type="{}mutasiRekeningType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataRekeningType", propOrder = {
    "infoRekening",
    "mutasiRekening"
})
public class DataRekeningType {

    protected InfoRekeningType infoRekening;
    protected List<MutasiRekeningType> mutasiRekening;

    /**
     * Gets the value of the infoRekening property.
     * 
     * @return
     *     possible object is
     *     {@link InfoRekeningType }
     *     
     */
    public InfoRekeningType getInfoRekening() {
        return infoRekening;
    }

    /**
     * Sets the value of the infoRekening property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoRekeningType }
     *     
     */
    public void setInfoRekening(InfoRekeningType value) {
        this.infoRekening = value;
    }

    /**
     * Gets the value of the mutasiRekening property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mutasiRekening property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMutasiRekening().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MutasiRekeningType }
     * 
     * 
     */
    public List<MutasiRekeningType> getMutasiRekening() {
        if (mutasiRekening == null) {
            mutasiRekening = new ArrayList<MutasiRekeningType>();
        }
        return this.mutasiRekening;
    }

}
