//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.06 at 10:07:24 AM ICT 
//


package com.xmlwriter.example.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for infoRekeningType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="infoRekeningType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cif" type="{}idType"/>
 *         &lt;element name="noRekening" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="namaRekening" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mataUang" type="{}currType"/>
 *         &lt;element name="statusRekening">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="01"/>
 *               &lt;enumeration value="02"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tglBukaRek" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="tglTutupRek" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="tglAwal" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="tglAkhir" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="saldoAwal" type="{}nilaiType"/>
 *         &lt;element name="saldoAkhir" type="{}nilaiType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "infoRekeningType", propOrder = {
    "cif",
    "noRekening",
    "namaRekening",
    "mataUang",
    "statusRekening",
    "tglBukaRek",
    "tglTutupRek",
    "tglAwal",
    "tglAkhir",
    "saldoAwal",
    "saldoAkhir"
})
public class InfoRekeningType {

    @XmlElement(required = true)
    protected String cif;
    @XmlElement(required = true)
    protected String noRekening;
    @XmlElement(required = true)
    protected String namaRekening;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CurrType mataUang;
    @XmlElement(required = true)
    protected String statusRekening;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tglBukaRek;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tglTutupRek;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tglAwal;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tglAkhir;
    @XmlElement(required = true)
    protected BigDecimal saldoAwal;
    @XmlElement(required = true)
    protected BigDecimal saldoAkhir;

    /**
     * Gets the value of the cif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCif() {
        return cif;
    }

    /**
     * Sets the value of the cif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCif(String value) {
        this.cif = value;
    }

    /**
     * Gets the value of the noRekening property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoRekening() {
        return noRekening;
    }

    /**
     * Sets the value of the noRekening property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoRekening(String value) {
        this.noRekening = value;
    }

    /**
     * Gets the value of the namaRekening property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamaRekening() {
        return namaRekening;
    }

    /**
     * Sets the value of the namaRekening property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamaRekening(String value) {
        this.namaRekening = value;
    }

    /**
     * Gets the value of the mataUang property.
     * 
     * @return
     *     possible object is
     *     {@link CurrType }
     *     
     */
    public CurrType getMataUang() {
        return mataUang;
    }

    /**
     * Sets the value of the mataUang property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrType }
     *     
     */
    public void setMataUang(CurrType value) {
        this.mataUang = value;
    }

    /**
     * Gets the value of the statusRekening property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusRekening() {
        return statusRekening;
    }

    /**
     * Sets the value of the statusRekening property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusRekening(String value) {
        this.statusRekening = value;
    }

    /**
     * Gets the value of the tglBukaRek property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTglBukaRek() {
        return tglBukaRek;
    }

    /**
     * Sets the value of the tglBukaRek property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTglBukaRek(XMLGregorianCalendar value) {
        this.tglBukaRek = value;
    }

    /**
     * Gets the value of the tglTutupRek property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTglTutupRek() {
        return tglTutupRek;
    }

    /**
     * Sets the value of the tglTutupRek property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTglTutupRek(XMLGregorianCalendar value) {
        this.tglTutupRek = value;
    }

    /**
     * Gets the value of the tglAwal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTglAwal() {
        return tglAwal;
    }

    /**
     * Sets the value of the tglAwal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTglAwal(XMLGregorianCalendar value) {
        this.tglAwal = value;
    }

    /**
     * Gets the value of the tglAkhir property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTglAkhir() {
        return tglAkhir;
    }

    /**
     * Sets the value of the tglAkhir property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTglAkhir(XMLGregorianCalendar value) {
        this.tglAkhir = value;
    }

    /**
     * Gets the value of the saldoAwal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSaldoAwal() {
        return saldoAwal;
    }

    /**
     * Sets the value of the saldoAwal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSaldoAwal(BigDecimal value) {
        this.saldoAwal = value;
    }

    /**
     * Gets the value of the saldoAkhir property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSaldoAkhir() {
        return saldoAkhir;
    }

    /**
     * Sets the value of the saldoAkhir property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSaldoAkhir(BigDecimal value) {
        this.saldoAkhir = value;
    }

}
