//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.06 at 10:07:24 AM ICT 
//


package com.xmlwriter.example.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.go.pajak.model.respon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Respon_QNAME = new QName("", "respon");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.go.pajak.model.respon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponType }
     * 
     */
    public ResponType createResponType() {
        return new ResponType();
    }

    /**
     * Create an instance of {@link MutasiRekeningType }
     * 
     */
    public MutasiRekeningType createMutasiRekeningType() {
        return new MutasiRekeningType();
    }

    /**
     * Create an instance of {@link SuratJawabanType }
     * 
     */
    public SuratJawabanType createSuratJawabanType() {
        return new SuratJawabanType();
    }

    /**
     * Create an instance of {@link LjkType }
     * 
     */
    public LjkType createLjkType() {
        return new LjkType();
    }

    /**
     * Create an instance of {@link DataRekeningType }
     * 
     */
    public DataRekeningType createDataRekeningType() {
        return new DataRekeningType();
    }

    /**
     * Create an instance of {@link DataKeuanganType }
     * 
     */
    public DataKeuanganType createDataKeuanganType() {
        return new DataKeuanganType();
    }

    /**
     * Create an instance of {@link ResponPermintaanType }
     * 
     */
    public ResponPermintaanType createResponPermintaanType() {
        return new ResponPermintaanType();
    }

    /**
     * Create an instance of {@link InfoRekeningType }
     * 
     */
    public InfoRekeningType createInfoRekeningType() {
        return new InfoRekeningType();
    }

    /**
     * Create an instance of {@link ResponDataType }
     * 
     */
    public ResponDataType createResponDataType() {
        return new ResponDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "respon")
    public JAXBElement<ResponType> createRespon(ResponType value) {
        return new JAXBElement<ResponType>(_Respon_QNAME, ResponType.class, null, value);
    }

}
