//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.06 at 10:07:24 AM ICT 
//


package com.xmlwriter.example.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for responDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="responDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="npwp" type="{}npwpType"/>
 *         &lt;element name="nik" type="{}idType" minOccurs="0"/>
 *         &lt;element name="namaWp" type="{}namaType"/>
 *         &lt;element name="statusNasabah">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dataKeuangan" type="{}dataKeuanganType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responDataType", propOrder = {
    "npwp",
    "nik",
    "namaWp",
    "statusNasabah",
    "dataKeuangan"
})
public class ResponDataType {

    @XmlElement(required = true)
    protected String npwp;
    protected String nik;
    @XmlElement(required = true)
    protected String namaWp;
    @XmlElement(required = true)
    protected String statusNasabah;
    protected DataKeuanganType dataKeuangan;

    /**
     * Gets the value of the npwp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpwp() {
        return npwp;
    }

    /**
     * Sets the value of the npwp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpwp(String value) {
        this.npwp = value;
    }

    /**
     * Gets the value of the nik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNik() {
        return nik;
    }

    /**
     * Sets the value of the nik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNik(String value) {
        this.nik = value;
    }

    /**
     * Gets the value of the namaWp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamaWp() {
        return namaWp;
    }

    /**
     * Sets the value of the namaWp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamaWp(String value) {
        this.namaWp = value;
    }

    /**
     * Gets the value of the statusNasabah property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusNasabah() {
        return statusNasabah;
    }

    /**
     * Sets the value of the statusNasabah property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusNasabah(String value) {
        this.statusNasabah = value;
    }

    /**
     * Gets the value of the dataKeuangan property.
     * 
     * @return
     *     possible object is
     *     {@link DataKeuanganType }
     *     
     */
    public DataKeuanganType getDataKeuangan() {
        return dataKeuangan;
    }

    /**
     * Sets the value of the dataKeuangan property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataKeuanganType }
     *     
     */
    public void setDataKeuangan(DataKeuanganType value) {
        this.dataKeuangan = value;
    }

}
