//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.06 at 10:07:24 AM ICT 
//


package com.xmlwriter.example.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for suratJawabanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="suratJawabanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="noRespon" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tglRespon" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="noSuratPermintaan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusRespon">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="00"/>
 *               &lt;enumeration value="01"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="namaPj" type="{}namaType"/>
 *         &lt;element name="jabatanPj" type="{}namaType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "suratJawabanType", propOrder = {
    "noRespon",
    "tglRespon",
    "noSuratPermintaan",
    "statusRespon",
    "namaPj",
    "jabatanPj"
})
public class SuratJawabanType {

    @XmlElement(required = true)
    protected String noRespon;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tglRespon;
    @XmlElement(required = true)
    protected String noSuratPermintaan;
    @XmlElement(required = true)
    protected String statusRespon;
    @XmlElement(required = true)
    protected String namaPj;
    @XmlElement(required = true)
    protected String jabatanPj;

    /**
     * Gets the value of the noRespon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoRespon() {
        return noRespon;
    }

    /**
     * Sets the value of the noRespon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoRespon(String value) {
        this.noRespon = value;
    }

    /**
     * Gets the value of the tglRespon property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTglRespon() {
        return tglRespon;
    }

    /**
     * Sets the value of the tglRespon property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTglRespon(XMLGregorianCalendar value) {
        this.tglRespon = value;
    }

    /**
     * Gets the value of the noSuratPermintaan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoSuratPermintaan() {
        return noSuratPermintaan;
    }

    /**
     * Sets the value of the noSuratPermintaan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoSuratPermintaan(String value) {
        this.noSuratPermintaan = value;
    }

    /**
     * Gets the value of the statusRespon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusRespon() {
        return statusRespon;
    }

    /**
     * Sets the value of the statusRespon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusRespon(String value) {
        this.statusRespon = value;
    }

    /**
     * Gets the value of the namaPj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamaPj() {
        return namaPj;
    }

    /**
     * Sets the value of the namaPj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamaPj(String value) {
        this.namaPj = value;
    }

    /**
     * Gets the value of the jabatanPj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJabatanPj() {
        return jabatanPj;
    }

    /**
     * Sets the value of the jabatanPj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJabatanPj(String value) {
        this.jabatanPj = value;
    }

}
